### ISSUE TITLE
Mesos Elastic search Executor Heap Space

### ISSUE THREAD

**Issue by gsvijayraajaa** [mesosphere/elasticsearch-mesos#19]
HI,

I am able to set the heap memory space for the scheduler via  "--elasticsearchRam" parameter in the marathon yml file. How do I set the memory of the executors?

The env variable given below didnt work as well:

```
env": {
    "JAVA_OPTS": "-Xms5g -Xmx15g"
  }
```

Regards,
Vijay Raajaa G S

**Comment by ssk2** [comment]
HI @gsvijayraajaa: is this the right repo for your query? This project has been deprecated so I'm going to close this issue for now.
